name: Test Package

on:
  push:
    branches:
      - dev
      - task-1
      - task-2
      - task-3

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            shell: bash -l {0}
    
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
            python-version: 3.9
            mamba-version: "*"
            channels: conda-forge,anaconda
            auto-update-conda: false
      - run: |
          mamba install conda-lock
          conda-lock render --kind env conda-lock.yml
          mamba env update --file conda-linux-64.lock.yml
          python -m pip install --upgrade pip
          pip install . --no-deps
          pytest
          pytest grading
